# fly.toml app configuration file generated for gitea-server-aarulabs on 2025-05-29T15:48:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gitea-server-aarulabs'
primary_region = 'fra'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '40gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
